import Head from "next/head";
import PageHeading from "../components/PageHeading";

const FAQ = () => {
	return (
		<div>
			<span className="hidden lg:block">
				<PageHeading text="Frequently Asked Questions" />
			</span>
			<span className="lg:hidden">
				<PageHeading text="FAQ" overwriteStyles="text-5xl font-bold" />
			</span>
			<p className="px-20 text-gray-600">
				Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae nulla earum ratione quibusdam, ea voluptas, libero illum amet est eius corrupti. Inventore architecto repudiandae totam itaque quis doloremque natus in quasi ex animi veniam quaerat vel distinctio minima ipsa veritatis quos voluptatum, aliquam ea blanditiis amet ad illo, commodi accusamus. Rerum, quo voluptates assumenda explicabo iste doloremque corporis dignissimos sunt, magnam officiis error non. Eos, est mollitia? Explicabo autem similique quis dignissimos asperiores, enim blanditiis sint rerum praesentium error quisquam minus molestiae quia doloribus aliquid officia illum vero distinctio consectetur labore harum accusamus tempore sequi ipsam. Ad, nulla? Repellendus est consectetur animi soluta architecto sit consequatur eaque molestias qui, consequuntur earum, nobis fuga, totam voluptatum labore. Vero quas eveniet cupiditate, enim dolores, quos in architecto iure ullam error impedit et doloremque, saepe maiores dolor temporibus voluptates. Autem, animi aliquam delectus quia reprehenderit earum eaque aliquid ea architecto tenetur eveniet, nostrum sunt illum deleniti doloremque? Incidunt et corrupti at, commodi earum ipsam eum eius natus fuga sapiente sunt aspernatur veniam labore accusantium quas enim excepturi assumenda omnis culpa exercitationem, ipsa autem ab quibusdam. Animi quo facilis velit sunt, fugit debitis perferendis similique aspernatur asperiores consectetur aliquid et, ratione, totam maxime quibusdam consequuntur a. Hic facilis accusamus maiores, vitae amet earum aspernatur. Quas voluptates consectetur recusandae non voluptatibus voluptatem in, dicta nisi ea eligendi quidem necessitatibus saepe nemo distinctio aut nesciunt? Atque eligendi iusto neque, iste quidem dignissimos? Blanditiis alias accusamus consequatur omnis consequuntur perspiciatis fugiat officiis sit, dolor ratione velit nobis sequi nostrum minus atque nesciunt? Asperiores aliquam pariatur dolor odio corrupti
				porro corporis? Esse atque ad sapiente at, vitae facilis, nemo repudiandae amet, aliquam dolorem ipsum ex quibusdam numquam minus. Suscipit atque nihil magni, delectus consequatur illum totam dolor culpa error corporis unde saepe amet, sunt deleniti, repudiandae natus nam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita molestias cum rem, iure consequuntur cupiditate voluptatibus maxime. Cumque molestias nobis rerum voluptatum. Quod aut aperiam nisi sit? Pariatur, iusto. Nihil harum unde minus, consectetur velit, nemo voluptatem numquam provident saepe praesentium vel voluptate fugit dolorem ad molestiae illo alias aspernatur maiores blanditiis facilis veritatis suscipit. Laudantium rem alias expedita placeat iure quis, provident nemo voluptates adipisci sequi iusto veniam cum molestias quo consequatur quaerat dignissimos ipsam numquam excepturi ducimus doloremque, illum temporibus inventore! At hic quidem molestiae ipsam cum? Voluptatum est fugiat alias animi maiores cupiditate rerum, blanditiis minima odio corrupti, itaque et quae amet delectus reprehenderit, tenetur expedita accusantium possimus nesciunt atque aspernatur dolorem ex mollitia repudiandae. Sit optio atque veniam exercitationem nulla sapiente iusto, fugiat laborum assumenda architecto esse? Iusto, placeat quas! Eos aliquid non reprehenderit? Cupiditate molestiae suscipit doloremque id amet consectetur fuga dolore accusantium nulla! Quos explicabo quasi esse magni fuga, id quibusdam temporibus, sed nihil animi adipisci doloribus! A voluptatibus eum ad itaque, laudantium iure consequuntur modi ipsum aliquam vitae nulla. Quam error aliquid debitis cupiditate nam, asperiores omnis quisquam? Nisi, illum quo quidem animi dolorum, similique dignissimos et quibusdam inventore porro officiis est natus. Excepturi magnam iusto rem ea nihil veritatis dignissimos nisi, sed voluptatibus error nesciunt aliquam at illo, laboriosam praesentium! Consequuntur, explicabo veritatis sed vel vitae
				temporibus qui laboriosam repellat, esse facere deleniti voluptate molestiae architecto numquam quibusdam a tempora optio blanditiis fugit voluptatem. Quo quos, officia vitae dolores velit, aliquid tempore veniam earum nisi, necessitatibus harum quisquam cupiditate dignissimos deserunt quas laboriosam delectus reprehenderit nobis asperiores mollitia! Minus, reiciendis ipsa soluta ab ea facere dolorem nihil delectus unde voluptatem! Nisi, cumque! Enim assumenda cum fugiat praesentium dolores incidunt ea, nemo voluptatum, distinctio atque, quidem delectus iure similique sequi! Repellendus dolor ratione officiis aspernatur, veritatis deserunt. Dolorem quibusdam, atque cumque eius odio non libero accusantium quos culpa, error earum inventore magni alias recusandae possimus laboriosam impedit, maiores eligendi aperiam neque tempora ducimus delectus? Voluptatibus maxime dolorem, aut repellat illo sequi sunt similique asperiores quia atque consequuntur, earum temporibus, sint repellendus mollitia velit voluptas recusandae. Fugit itaque quas repellendus dolore cumque, at, nisi, eaque cupiditate laborum impedit mollitia dignissimos! Recusandae cupiditate soluta vitae, facilis pariatur maiores illo rerum esse maxime, cumque, nemo nisi asperiores dolorem porro! Soluta dolore quae odio reprehenderit molestiae vel mollitia voluptatibus in debitis sunt ipsa maxime nihil tempore delectus nisi neque nam, commodi distinctio doloremque nemo? Sit obcaecati possimus commodi beatae, at praesentium voluptates molestias dolore incidunt delectus perferendis officia deleniti libero maiores sunt eius vitae doloremque impedit a minus? Voluptate laudantium tenetur eius, eveniet ducimus vitae maxime quia accusamus quaerat quidem? Qui eligendi odio doloribus, ad, ex nulla ullam dignissimos praesentium eaque facere assumenda perferendis incidunt at repudiandae impedit dolores voluptatum similique hic voluptatem officia. Sint aspernatur nulla magni adipisci soluta corporis ut alias
				voluptates incidunt id? Earum illo reiciendis alias, quam tempora doloribus porro fuga debitis. Repellendus minus nulla similique repudiandae voluptatibus quasi, dolorem explicabo amet et.
			</p>
		</div>
	);
};

export default FAQ;
