import Head from "next/head";
import PageHeading from "../components/Layout/PageHeading";


const Team = () => {
	return (
		<div>
			<PageHeading text="Team" />
			<p className="px-20 text-gray-600">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti quasi qui dolore velit excepturi minima amet debitis? Mollitia veritatis maiores adipisci consequuntur, dignissimos eaque deserunt totam error laborum labore. Fugiat doloribus expedita nesciunt impedit voluptas numquam sunt cum ipsam nihil veritatis culpa quasi praesentium vero sequi, voluptates nam deserunt quaerat nobis perferendis enim neque possimus! Sunt accusantium iste aut delectus vitae, adipisci ea amet, at quibusdam laborum ullam laudantium pariatur a doloremque quisquam ex ut nisi quos accusamus qui modi ducimus, tenetur quam similique? Molestiae neque et earum rerum fuga minus sapiente quam vitae fugit qui, doloremque sunt eos temporibus reiciendis id nostrum consequuntur autem odit non quidem aliquid voluptatem nesciunt. Accusantium, aliquam consectetur. Tempore dolor mollitia beatae fugiat rem deserunt nemo, natus eaque odio placeat dignissimos unde nesciunt alias, ab, quaerat omnis nihil ut accusantium ipsum delectus? Vitae aliquam assumenda ut dolorem aspernatur, excepturi explicabo veritatis, nisi facere quam voluptatum ullam accusantium, natus necessitatibus sed voluptates magnam impedit asperiores. Eius nobis facere totam, consectetur aut debitis iusto numquam deserunt ipsa at aliquam vitae doloribus cupiditate libero eligendi. Labore aperiam libero debitis cumque a sapiente suscipit rerum, enim nihil eius, assumenda voluptatibus nesciunt voluptatem quasi eveniet molestiae quam officiis, soluta iste adipisci earum deleniti? Nesciunt odit praesentium ducimus laboriosam doloremque dolores beatae non corporis iste impedit officiis magnam, inventore assumenda similique architecto obcaecati laudantium repellat. Doloribus quis architecto dolore quo unde consequuntur quam voluptates ut, exercitationem voluptatum, eligendi facere perspiciatis rem est? Nihil possimus natus aliquid, similique nobis autem sint molestiae non laboriosam quod consequuntur ratione et expedita aspernatur
				maxime est! Voluptatibus recusandae esse reprehenderit aperiam impedit quis? Voluptates libero commodi ullam deserunt maiores quo, tenetur in vel laudantium voluptate placeat debitis distinctio tempore rerum odit incidunt vero, officia sequi! Veniam temporibus porro culpa nihil? Facere quos ratione aperiam itaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed, corporis incidunt? Repudiandae earum minima iusto! Officia dolorum fugit nisi atque, tempore consequatur, amet quasi, fugiat doloremque impedit itaque maxime inventore quo quam? Eligendi itaque quibusdam praesentium cupiditate libero at, aliquam facere quia similique optio neque inventore quidem rem dolores culpa. Molestias modi quia unde est atque ad dignissimos nisi possimus eveniet beatae saepe, ut libero incidunt necessitatibus? Tempora, aperiam porro voluptates necessitatibus sapiente magni deleniti pariatur. Repudiandae nulla possimus magni ad fugit soluta libero doloribus ipsa expedita alias doloremque facere aliquam esse id exercitationem, labore deserunt. Sed officia rem, explicabo, pariatur vel minus aspernatur nam in similique reiciendis officiis ex magni voluptate. Tempora, cupiditate praesentium architecto culpa minus voluptate ratione atque excepturi soluta dolore adipisci dolorum dicta ullam quaerat sint voluptatum error blanditiis, molestias voluptates rem! Hic expedita perferendis in veritatis deserunt, recusandae, voluptatum reiciendis laborum nesciunt commodi asperiores ea doloribus nihil, explicabo sed eum neque laudantium. Corporis voluptatibus officia vel ducimus quo, repellat alias quidem delectus nobis quasi. Similique dolor necessitatibus perspiciatis et perferendis fuga sed minus culpa veritatis cum deserunt atque accusantium corporis amet rem, alias reprehenderit saepe! Quos laborum laboriosam voluptatibus corrupti quibusdam velit, id necessitatibus magnam iure repellat amet tempore numquam earum voluptatum facere nobis dolor recusandae odit quis rerum maiores
				porro ab! Sequi, amet? Dolorum illo ipsa non suscipit aliquam deleniti ex fugit excepturi? Culpa cum excepturi nulla eius eos modi vel dolorem velit ex quasi nam molestiae recusandae facilis beatae, earum harum, nobis mollitia? Deleniti id vel nesciunt repudiandae nam iure architecto quis repellendus vero quaerat, ab ad incidunt blanditiis explicabo beatae provident fugit obcaecati atque laborum exercitationem? Laboriosam incidunt minima possimus cum earum velit atque, dignissimos quae ratione rerum exercitationem soluta quas quam eius, neque assumenda officia? Aspernatur necessitatibus, esse eaque sapiente consequatur, a maxime expedita itaque ea laborum saepe voluptatibus. Optio minus quidem, ullam, eos odit quae animi magni aliquid omnis veritatis delectus necessitatibus quod deserunt. Accusantium libero officiis nisi sed voluptatum ab, aut laboriosam possimus amet quibusdam quo perferendis error reprehenderit placeat ducimus beatae, asperiores dolorum fugit molestias est similique sit quidem. Incidunt temporibus repellendus placeat culpa esse impedit assumenda quibusdam, iste aut perferendis voluptatibus illo maxime unde inventore provident dolor nulla, consectetur alias dolorem sint vel nesciunt. Voluptatum nostrum accusamus similique, provident autem corrupti quas, beatae architecto saepe eum voluptates doloremque veritatis a pariatur quia soluta. Veniam ad quod exercitationem aspernatur incidunt alias vel dolorem accusantium voluptas aut ea, facilis saepe! Totam maxime cumque eveniet porro dignissimos hic fugit modi et omnis error, enim accusamus praesentium nisi molestiae laborum voluptates illum minus itaque deserunt accusantium voluptatem suscipit quia! At exercitationem, explicabo possimus debitis alias voluptates deserunt corporis quidem esse molestias, dignissimos quaerat architecto nostrum earum sit? Sed, animi velit repudiandae deserunt explicabo nostrum facilis, labore odio quo esse illo minus tempore nam aut quas commodi, voluptatum
				temporibus reiciendis voluptatibus dolore illum provident ad. Veniam qui, hic itaque, reiciendis quas repellendus ut sequi cupiditate debitis maxime fugiat. Eos, excepturi dolorum. Nobis.
			</p>
		</div>
	);
};

export default Team;
